services:
  lana-paper-wallet:
    build: .
    container_name: lana-paper-wallet
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=www.lanapaper.online,lanapaper.online
      - LETSENCRYPT_HOST=www.lanapaper.online,lanapaper.online
      - LETSENCRYPT_EMAIL=josh@lanaworld.app
    networks:
      - webproxy

networks:
  webproxy:
    external: true
